# Generated by Django 4.2.21 on 2026-03-11 20:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="solutions.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="CostLevel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(max_length=20, unique=True)),
                ("description", models.CharField(max_length=200)),
                (
                    "min_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolutionType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Timeframe",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.CharField(max_length=20, unique=True)),
                ("description", models.CharField(max_length=200)),
                ("min_years", models.IntegerField(blank=True, null=True)),
                ("max_years", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("region", models.CharField(max_length=100)),
                ("climate_zone", models.CharField(max_length=50)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["country", "region"],
                        name="solutions_l_country_bb0e99_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ClimateSolution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("benefits", models.TextField()),
                (
                    "source_url",
                    models.URLField(validators=[django.core.validators.URLValidator()]),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="solutions.category",
                    ),
                ),
                (
                    "cost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="solutions.costlevel",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="solutions.location",
                    ),
                ),
                (
                    "solution_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="solutions.solutiontype",
                    ),
                ),
                (
                    "timeframe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="solutions.timeframe",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="solutions_c_name_31e119_idx"),
                    models.Index(
                        fields=["category", "location"],
                        name="solutions_c_categor_bf9625_idx",
                    ),
                    models.Index(
                        fields=["cost", "timeframe"],
                        name="solutions_c_cost_id_d0230d_idx",
                    ),
                ],
            },
        ),
    ]
